# 직업병 연구방법론 개론 {.unnumbered}
```{r setup, echo=FALSE}
knitr::opts_chunk$set(message=FALSE, warning = FALSE, echo = FALSE)
```
## 보건학 우선순위

 가장 간단한 질병의 발생 또는 건강 악화의 구조는 병인과 질병입니다. **원인 물질에 노출된다 그리고 발생한다.** 입니다. 
 


<center>
```{r,   out.width="40%", out.height="40%", fig.cap="노출과 질병",dev='png'}
if(!require(DiagrammeR)) install.packages('DiagrammeR')
DiagrammeR::grViz(
  "digraph nicegraph { 
  graph[rankdir = LR]
  Exposure -> Disease
  }" )
```
</center>

 
&nbsp; WHO 에서는 

1. 건강에 영향을 주는 구조적 차이 (Systemic Difference)가,
2. 피할 수 있는데 (be avoidable), 
3. 불공정(unfair) 할 때, 

  &rightarrow; 건강비형평성 (heath Inequity) 이 있다고 이야기합니다. 

&nbsp; 이를 고려하여 노출에 대해서 고민해 보겠습니다. 그렇다면 노출을 피할 수 있는데, 그렇지 못한 것이 불공정할 때 보건학적 우선순위가 될 수 있습니다. 개인적 습관은 어디에, 직업적 노출은 어디에 속할 까요?


```{r priority1, table.cap="건강형평성 관점의 보건학 우선 순위"}
library(tidyverse)
library(kableExtra)
data.frame(row.names = c('be avoidable', 'not be avoidable'), 
           "Unfair" = c("High Priority", ""), "Fair"=c("", "Low Priority")
           ) %>%
  kbl(caption = "건강형평성 관점의 보건학 우선 순위") %>%
  kable_paper(full_width  = F) %>%
  column_spec(1:3, border_right = T, color = 'grey') %>%
  column_spec(2, color ="blue", bold = T)
```



